/**
 * Generates a SQL file with INSERT statements for all demo seed data.
 *
 * Run: npx tsx supabase/generate-seed-sql.ts
 * Output: supabase/seed-data.sql
 */

import { demoEstimationRuns, demoAdjustments, demoOutcomes } from '../src/demo/seed';
import { writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

function esc(val: unknown): string {
  if (val === null || val === undefined) return 'NULL';
  if (typeof val === 'number') return String(val);
  if (typeof val === 'object') return `'${JSON.stringify(val).replace(/'/g, "''")}'::jsonb`;
  return `'${String(val).replace(/'/g, "''")}'`;
}

const lines: string[] = [
  '-- Auto-generated seed data for Mason Home Services demo account',
  '-- Generated by: npx tsx supabase/generate-seed-sql.ts',
  `-- Generated at: ${new Date().toISOString()}`,
  '',
  '-- Run schema.sql FIRST, then this file.',
  '',
  '-- ─── Estimation Runs ───',
  '',
];

for (const run of demoEstimationRuns) {
  lines.push(`INSERT INTO estimation_runs (id, business_id, work_id, created_at, project_family, estimator_version, ai_model, prompt_version, customer_inputs, extraction, baseline_estimate, calibration_applied, economic_job, decision_context, recommendation, reasons, confidence) VALUES (${esc(run.id)}, ${esc(run.businessId)}, ${run.workId ?? 'NULL'}, ${esc(run.createdAt)}, ${esc(run.projectFamily)}, ${esc(run.estimatorVersion)}, ${esc(run.aiModel)}, ${esc(run.promptVersion)}, ${esc(run.customerInputs)}, ${esc(run.extraction)}, ${esc(run.baselineEstimate)}, ${run.calibrationApplied ? esc(run.calibrationApplied) : 'NULL'}, ${esc(run.economicJob)}, ${esc(run.decisionContext)}, ${esc(run.recommendation)}, ${esc(run.reasons)}, ${run.confidence});`);
}

lines.push('', '-- ─── Adjustment Entries ───', '');

for (const adj of demoAdjustments) {
  lines.push(`INSERT INTO adjustment_entries (id, estimation_run_id, business_id, user_id, field, system_value, previous_value, new_value, reason_code, reason_text, created_at) VALUES (${esc(adj.id)}, ${esc(adj.estimationRunId)}, ${esc(adj.businessId)}, ${esc(adj.userId)}, ${esc(adj.field)}, ${adj.systemValue}, ${adj.previousValue}, ${adj.newValue}, ${esc(adj.reasonCode)}, ${adj.reasonText ? esc(adj.reasonText) : 'NULL'}, ${esc(adj.createdAt)});`);
}

lines.push('', '-- ─── Actual Outcomes ───', '');

for (const o of demoOutcomes) {
  lines.push(`INSERT INTO actual_outcomes (id, estimation_run_id, actual_labor_hours, actual_material_cost, actual_procurement_hours, final_revenue, return_trips, recorded_at, notes) VALUES (${esc(o.id)}, ${esc(o.estimationRunId)}, ${o.actualLaborHours}, ${o.actualMaterialCost}, ${o.actualProcurementHours}, ${o.finalRevenue}, ${o.returnTrips}, ${esc(o.recordedAt)}, ${o.notes ? esc(o.notes) : 'NULL'});`);
}

const output = lines.join('\n') + '\n';
const outPath = join(__dirname, 'seed-data.sql');
writeFileSync(outPath, output);
console.log(`Wrote ${demoEstimationRuns.length} runs, ${demoAdjustments.length} adjustments, ${demoOutcomes.length} outcomes to ${outPath}`);
