/**
 * Generates a SQL file with INSERT statements for all demo seed data.
 *
 * Run: npx tsx supabase/generate-seed-sql.ts
 * Output: supabase/seed-data.sql
 */

import { demoEstimationRuns, demoAdjustments, demoOutcomes, demoWorkItems } from '../src/demo/seed';
import { writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Mason Home Services deterministic UUID (matches seed-mason-data.sql)
const MASON_BIZ_ID = 'a0000000-0000-0000-0000-000000000001';

function esc(val: unknown): string {
  if (val === null || val === undefined) return 'NULL';
  if (typeof val === 'number') return String(val);
  if (typeof val === 'object') return `'${JSON.stringify(val).replace(/'/g, "''")}'::jsonb`;
  return `'${String(val).replace(/'/g, "''")}'`;
}

const lines: string[] = [
  '-- Auto-generated seed data for Mason Home Services demo account',
  '-- Generated by: npx tsx supabase/generate-seed-sql.ts',
  `-- Generated at: ${new Date().toISOString()}`,
  '',
  '-- Run all migrations + seed-demo-user.sql + seed-mason-data.sql FIRST, then this file.',
  '',
  '-- ─── Estimation Runs ───',
  '',
];

for (const run of demoEstimationRuns) {
  lines.push(`INSERT INTO estimation_runs (id, business_id, work_id, created_at, project_family, estimator_version, ai_model, prompt_version, customer_inputs, extraction, baseline_estimate, calibration_applied, economic_job, decision_context, recommendation, reasons, confidence) VALUES (${esc(run.id)}, ${esc(run.businessId)}, ${run.workId ?? 'NULL'}, ${esc(run.createdAt)}, ${esc(run.projectFamily)}, ${esc(run.estimatorVersion)}, ${esc(run.aiModel)}, ${esc(run.promptVersion)}, ${esc(run.customerInputs)}, ${esc(run.extraction)}, ${esc(run.baselineEstimate)}, ${run.calibrationApplied ? esc(run.calibrationApplied) : 'NULL'}, ${esc(run.economicJob)}, ${esc(run.decisionContext)}, ${esc(run.recommendation)}, ${esc(run.reasons)}, ${run.confidence});`);
}

lines.push('', '-- ─── Adjustment Entries ───', '');

for (const adj of demoAdjustments) {
  lines.push(`INSERT INTO adjustment_entries (id, estimation_run_id, business_id, user_id, field, system_value, previous_value, new_value, reason_code, reason_text, created_at) VALUES (${esc(adj.id)}, ${esc(adj.estimationRunId)}, ${esc(adj.businessId)}, ${esc(adj.userId)}, ${esc(adj.field)}, ${adj.systemValue}, ${adj.previousValue}, ${adj.newValue}, ${esc(adj.reasonCode)}, ${adj.reasonText ? esc(adj.reasonText) : 'NULL'}, ${esc(adj.createdAt)});`);
}

lines.push('', '-- ─── Actual Outcomes ───', '');

for (const o of demoOutcomes) {
  lines.push(`INSERT INTO actual_outcomes (id, estimation_run_id, actual_labor_hours, actual_material_cost, actual_procurement_hours, final_revenue, return_trips, recorded_at, notes) VALUES (${esc(o.id)}, ${esc(o.estimationRunId)}, ${o.actualLaborHours}, ${o.actualMaterialCost}, ${o.actualProcurementHours}, ${o.finalRevenue}, ${o.returnTrips}, ${esc(o.recordedAt)}, ${o.notes ? esc(o.notes) : 'NULL'});`);
}

lines.push('', '-- ─── Work Items ───', '');

for (const w of demoWorkItems) {
  lines.push(`INSERT INTO work_items (business_id, title, source, customer_type, customer_name, customer_sub, location, travel, profit, hours, hours_num, rate, rate_num, recommendation, confidence, description, price, costs, cost_breakdown, reasons, photos, op_status, billing_status, preferred_date, phone, email, address, customer_notes, company_name, property_name, unit_label, work_order_number, requested_by, requested_by_role, requested_date, scope, service_type, estimation_run_id) VALUES (${esc(MASON_BIZ_ID)}, ${esc(w.title)}, ${esc(w.source)}, ${esc(w.customerType)}, ${esc(w.customerName)}, ${w.customerSub ? esc(w.customerSub) : 'NULL'}, ${esc(w.location)}, ${esc(w.travel)}, ${w.profit}, ${esc(w.hours)}, ${w.hoursNum}, ${esc(w.rate)}, ${w.rateNum}, ${esc(w.recommendation)}, ${w.confidence}, ${esc(w.description)}, ${w.price}, ${w.costs}, ${esc(w.costBreakdown)}, ${esc(w.reasons)}, ${esc(w.photos)}, ${esc(w.opStatus)}, ${esc(w.billingStatus)}, ${w.preferredDate ? esc(w.preferredDate) : 'NULL'}, ${w.phone ? esc(w.phone) : 'NULL'}, ${w.email ? esc(w.email) : 'NULL'}, ${w.address ? esc(w.address) : 'NULL'}, ${w.customerNotes ? esc(w.customerNotes) : 'NULL'}, ${w.companyName ? esc(w.companyName) : 'NULL'}, ${w.propertyName ? esc(w.propertyName) : 'NULL'}, ${w.unitLabel ? esc(w.unitLabel) : 'NULL'}, ${w.workOrderNumber ? esc(w.workOrderNumber) : 'NULL'}, ${w.requestedBy ? esc(w.requestedBy) : 'NULL'}, ${w.requestedByRole ? esc(w.requestedByRole) : 'NULL'}, ${w.requestedDate ? esc(w.requestedDate) : 'NULL'}, ${w.scope ? esc(w.scope) : 'NULL'}, ${esc(w.serviceType)}, ${w.estimationRunId ? esc(w.estimationRunId) : 'NULL'});`);
}

const output = lines.join('\n') + '\n';
const outPath = join(__dirname, 'seed-data.sql');
writeFileSync(outPath, output);
console.log(`Wrote ${demoEstimationRuns.length} runs, ${demoAdjustments.length} adjustments, ${demoOutcomes.length} outcomes, ${demoWorkItems.length} work items to ${outPath}`);
